version: '2'

services:
  project:
    image: node:alpine3.11
    build: .
    working_dir: /usr/src/app/
    volumes:
      - ./dashboard:/usr/src/app/
    environment:
      NODE_ENV: development
    command: npm run start
    ports:
      - '3000:3000'
